Repository booksaetong/booksaetong, pull requests merged in 2025-01, with the labels that each got.

#22 [feat/search] 검색 페이지 api 통신 및 데이터 패칭
  src/app/components/Skeleton.tsx
  src/app/globals.css
  src/app/search/_components/BookListSkeleton.tsx
  src/app/search/_components/SearchBar.tsx
  src/app/search/_components/SearchResult.tsx
  src/app/search/page.tsx
  src/hooks/useDebounce.ts
  src/hooks/useSearchResult.ts
  src/libs/apis/searchApi.ts
  src/stores/searchResult.ts
  src/types/common.ts
Labels: 기능

#27 [Feat/bookshelf] 서재페이지 상세모달 연동
  src/app/bookshelf/components/BooksRow.tsx
  src/app/bookshelf/components/Container.tsx
  src/app/bookshelf/components/SortableItm.tsx
  src/app/bookshelf/page.tsx
  src/app/components/Spinner.tsx
  src/app/components/modal/Modal.tsx
  src/app/dnd/page.tsx
  src/stores/likedBooks.ts
Labels: 기능

#33 [Feat/search] Container/Presentational Pattern를 활용한 컴포넌트 재구성
  src/app/components/modal/Modal.tsx
  src/app/search/_components/Bookmark.tsx
  src/app/search/_components/DropDown.tsx
  src/app/search/_components/SearchResult.tsx
  src/app/search/_components/container/BookmarkContainer.tsx
  src/app/search/_components/container/DropDownContainer.tsx
  src/app/search/_components/container/SearchResultContainer.tsx
  src/app/search/_components/presentation/BookmarkUI.tsx
  src/app/search/_components/presentation/DropDownUI.tsx
  src/app/search/_components/presentation/SearchResultUI.tsx
  src/app/search/page.tsx
  tailwind.config.ts
Labels: 수정

#43 [Feat/search] pagination 구현
  public/icons/PageArrow.svg
  public/icons/PageDoubleArrow.svg
  src/app/components/IconButton.tsx
  src/app/components/Navbar.tsx
  src/app/components/SearchBar.tsx
  src/app/search/_components/Pagination.tsx
  src/app/search/_components/container/BookmarkContainer.tsx
  src/app/search/_components/container/DropDownContainer.tsx
  src/app/search/_components/container/SearchResultContainer.tsx
  src/app/search/_components/presentation/Bookmark.tsx
  src/app/search/_components/presentation/BookmarkUI.tsx
  src/app/search/_components/presentation/DropDown.tsx
  src/app/search/_components/presentation/SearchResult.tsx
  src/app/search/_components/presentation/SearchResultUI.tsx
  src/app/search/page.tsx
  src/hooks/useSearchBooks.ts
  src/libs/apis/searchApi.ts
  src/stores/searchResult.ts
  src/stores/searchStore.ts
  src/types/common.ts
Labels: 기능, 수정
